### ISSUE TITLE
Util.go

### ISSUE THREAD

**Issue by Nova27** [bitbandi/decred-proxy#2]
Hi! I have an error when i compiling on util.go : line 106 undefined: blockchain.ShaHashToBig

**Comment by Merratzz** [comment]
I`am too. Somebody can help?

**Comment by bitbandi** [comment]
Fixed in https://github.com/bitbandi/decred-proxy/commit/fc61f4c24c4d0580e262e9c195069624a23cc87a .

**Comment by Merratzz** [comment]
Ok thanks for help.

Now i have a new error when do  -> go build -o decred-proxy main.go

Error:
rpc/rpc.go:68: unknown http.Client field 'Timeout' in struct literal 

Any Idea? Can you build it correctly?

**Comment by bitbandi** [comment]
maybe old golang version.

**Comment by Merratzz** [comment]
i have tried with Different versions, also with go1.4  (i use gvm for it)

**Comment by bitbandi** [comment]
golang 1.4.3 sould be ok:


```
# ../go/bin/go version
go version go1.4.3 linux/amd64
# ../go/bin/go build -v
decred-proxy/rpc
...
decred-proxy/util
decred-proxy/proxy
decred-proxy
#
```

**Comment by Merratzz** [comment]
Ok now it works, you have right. Was the false go version active. Thanks for your help
